server:
  servlet:
    context-path: /ctms-api
  port: 9900
  shutdown: graceful

customer:
  profile:
    api:
      url: https://api.customerprofile.com/tariff-plan

spring:
  datasource:
    url: jdbc:postgresql://${pg_host:localhost}:${pg_port:5432}/${pg_db:ctms_pad}
    username: ${pg_user:postgres}
    password: ${pg_pwd:postgres}
  profiles:
    active: default

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
info:
  pod: ${HOSTNAME:null}
