server:
  servlet:
    context-path: /ctms-api
  port: 9900
  shutdown: graceful

customer:
  profile:
    api:
      url: https://api.customerprofile.com/tariff-plan

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ctms_pad
    username: postgres
    password: postgres
  profiles:
    active: default
